# -*- coding: utf-8 -*-
"""AK_logistic_Mapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BKBghl6Ora3k7fonouUu-yOuJeXmH2P1
"""

import numpy as np
import matplotlib.pyplot as plt

n=100
x=0.5
r=0.8
a=np.zeros(n)
i=0
while(i<n):
    a[i]=r*x*(1-x)
    x=r*x*(1-x)
    i=i+1
t=np.linspace(0,n-1,n)
plt.plot(t,a)

r=2.8
a=np.zeros(n)
i=0
while(i<n):
    a[i]=r*x*(1-x)
    x=r*x*(1-x)
    i=i+1
t=np.linspace(0,n-1,n)
plt.plot(t,a)

r=3.2
a=np.zeros(n)
i=0
while(i<n):
    a[i]=r*x*(1-x)
    x=r*x*(1-x)
    i=i+1
t=np.linspace(0,n-1,n)
plt.plot(t,a)

r=3.5
a=np.zeros(n)
i=0
while(i<n):
    a[i]=r*x*(1-x)
    x=r*x*(1-x)
    i=i+1
t=np.linspace(0,n-1,n)
plt.plot(t,a)



r=3.8
a=np.zeros(n)
i=0
while(i<n):
    a[i]=r*x*(1-x)
    x=r*x*(1-x)
    i=i+1
t=np.linspace(0,n-1,n)
plt.plot(t,a)