# -*- coding: utf-8 -*-
"""Logistic Map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ok2WcWvNltS9LG8RWGBhShx-e7562xb3
"""

# Commented out IPython magic to ensure Python compatibility.
# Himanshu
# SC18B013
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

def logistic(r, x):
    return r*x*(1 - x)

x = np.linspace(0, 1)
fig, ax = plt.subplots(1, 1)
ax.plot(x, logistic(2, x), 'k')

def plot_system(r,x0,n,ax=None):
    t = np.linspace(0,1)
    ax.plot(t, logistic(r, t), 'k', lw=2)
    ax.plot([0, 1], [0, 1], 'k', lw=2)

    x = x0
    for i in range(n):
        y = logistic(r, x)
        ax.plot([x, x], [x, y], 'k', lw=1)
        ax.plot([x, y], [y, y], 'k', lw=1)
        ax.plot([x], [y], 'ok', ms=10,
                alpha=(i + 1) / n)
        x = y

    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.set_title(f"$r={r:.1f}, \, x_0={x0:.1f}$")

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6),
                               sharey=True)
plot_system(0.8, .1, 10, ax=ax1)
plot_system(2.8, .1, 10, ax=ax2)

fig, (ax3, ax4) = plt.subplots(1, 2, figsize=(12, 6), 
                               sharey=True)
plot_system(3.2, .1, 10, ax=ax3)
plot_system(3.8, .1, 10, ax=ax4)